import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fundsmith</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center">
        <div className="flex flex-col">
          <h1>👋 Hello there! What would you like to create today?</h1>
        </div>
      </div>
    </>
  );
}
